### ISSUE TITLE
It would be great to add TeamSpeak

### ISSUE THREAD

**Issue by schmitch** [fedy/fedy#256]
Hello, currently Teamspeak is also an App which runs on Linux however the only way to install it currently is to do it manually.

**Comment by Jobava** [comment]
That would also be great, but Teamspeak download is only available to those that sign an EULA, so there may have to be some cooperation from Teamspeak itself if they are to be added to Fedy.

**Comment by gitgt** [comment]
Are you talking about Client? It can be downloaded without EULA, for example from http://dl.4players.de/ts/releases/3.0.18/TeamSpeak3-Client-linux_x86-3.0.18.run or http://dl.4players.de/ts/releases/3.0.18/TeamSpeak3-Client-linux_amd64-3.0.18.run.

**Comment by metabsd** [comment]
Use Discord, it's a better solution.

https://discordapp.com/ :+1:

**Comment by bddenhartog** [comment]
@metabsd "better solution" is subjective; I think both pale in comparison to the quality of Mumble :)

If you'd like to see Discord in Fedy, please create a separate issue. Thank you!
