### ISSUE TITLE
Add Veracrypt

### ISSUE THREAD

**Issue by gitgt** [fedy/fedy#270]
Please consider adding Veracrypt. It's a GUI app, successor to TrueCrypt. 
Currently Realcrypt is available in Fedora repository but i'ts just a rebrand of TrueCrypt.

**Comment by bddenhartog** [comment]
@gitgt Does this still warrant looking into?

**Comment by gitgt** [comment]
@bddenhartog In my view, yes. It's nice and active: "Last Update: 2017-08-08".
RealCrypt's "no code relating to actual encryption or decryption is modified" and "Last Update: 2014-09-06".
There's also zuluCrypt but looks like KDE only. 
So, I'm not crypto expert but I'm in favor of veraCrypt.

**Comment by gitgt** [comment]
@bddenhartog In my view, yes. It's nice and active: "Last Update: 2017-08-08".
RealCrypt's "no code relating to actual encryption or decryption is modified" and "Last Update: 2014-09-06". 
Fedora has zuluCrypt (front end to cryptsetup and tcplay) in repository but GUI looks like KDE only.
So, I'm not crypto expert but I'm in favor of veraCrypt.
