### ISSUE TITLE
Suggestion: Video Acceleration packages

### ISSUE THREAD

**Issue by egriffith** [fedy/fedy#296]
Fedy already offers to install multimedia codecs, it seems reasonable to offer 

AMD, Intel and Nvidia hardware acceleration installation options. Given that some packages in the listing conflict with others, I would not recommend a general "Video playback" install button, but instead keep it separated out by vendor. I would be willing to create a list of packages necessary to get acceleration working, if the developers would be willing to then turn it into a plugin

**Comment by Abhinav1217** [comment]
We would love a Pull Request.

**Comment by DStewart1997** [comment]
@egriffith I could help you make the plugins if you know the packages.

**Comment by user501254** [comment]
@egriffith, are you suggesting to include proprietary drivers for these graphics manufacturers?

**Comment by satya164** [comment]
Installing drivers is very tricky, one wrong step and you might make your system boot without any graphical environment. It might be easy to troubleshoot for experienced users, but not for new users, towards whom Fedy is aimed at. We really don't want to take the risk.

However, there is a tool called Pharlap from the Korora folks, which is aimed at installing drivers. May be it could be added to Fedy.

**Comment by egriffith** [comment]
@user501254  Negative, unless vdpau, vaapi, and the libraries to interoperate count as "proprietary drivers."

**Comment by egriffith** [comment]
In order to get video accel working you the following packages

--Intel--
libvdpau
libva
vdpauinfo
libva-intel-driver
libvdpau-va-gl
libva-utils

--AMD and Nvidia--
libvdpau
libva
vdpauinfo
libva-utils
libva-vdpau-driver
mesa-vdpau-drivers

Note that you do -not- want to install libvdpau-va-gl on AMD & Nvidia platforms. 

The user will have working video acceleration if running the commands

vdpauinfo
vainfo 

both return a listing of entry points / codecs.

**Comment by rishadafc** [comment]
Fedora 23 already runs the latest Intel graphic drivers. Details [here](https://01.org/linuxgraphics/blogs/thac0/2015/fedora-23-users-no-need-graphics-installer-1.2.1).

**Comment by egriffith** [comment]
Hold on guys. 

@satya164 , none of these things should affect the boot process in any way. I get that these are labeled as "drivers" but we aren't replacing the users existing drivers. This isn't like installing the AMD or Nvidia closed source drivers. The drivers in the kernel already initialize the video hardware, these libraries just expose the capability to applications. 

Any crashes or issues would be exposed when they try to play a video, well past the boot process-- same as they currently would be when users install the Multimedia Codecs option that Fedy currently ships.

@rishadafc , Fedora doesn't ship the video accel part of the driver by default. Its out of rpmfusion-free

**Comment by rishadafc** [comment]
@egriffith Thanks for the clarification. Is the video acceleration part proprietary? Also, where is the impact of this video acceleration felt the most in terms of watching videos - videos in the browser or in a standalone player? I know VLC has support for it in the settings somewhere, and Firefox has a hardware acceleration checkbox in its preferences.

**Comment by jurf** [comment]
No part of video acceleration is proprietary, unless you are using proprietary video drivers. VDPAU and VA-API both have open implementations. The [Arch Wiki](https://wiki.archlinux.org/index.php/Hardware_video_acceleration] explains how it works quite well (shameless self-pat-on-the-back, haha).
