### ISSUE TITLE
"Better font rendering" Tweak with xsetting schema fails

### ISSUE THREAD

**Issue by xmetax** [fedy/fedy#313]
I am running F23 on Cinnamon.

When I click "Setup" for Better font rendering, the task is reported as Failed. Freetype-freeworld is installed and has the /etc/fonts/local.conf file created. I am still a novice, so please let me know if you require additional info. 

Thanks.

**Comment by Abhinav1217** [comment]
Can you put content of `/etc/fonts/local.conf` here.  There is nothing else to do. Maybe it just reported failed but has actually done its job.

**Comment by Abhinav1217** [comment]
On other thought, open terminal and sun `sudo fedy` and then perform the task.  After that paste the content of the terminal here. Maybe there is some failed repo url.

**Comment by xmetax** [comment]
Here's the output: 

Last metadata expiration check performed 1:36:38 ago on Sat Dec 19 16:06:44 2015.
Dependencies resolved.
==============================================================================================================================================
 Package                              Arch                 Version                         Repository                                    Size
==============================================================================================================================================
Installing:
 fedy-font-config                     noarch               1.0.1-1.fc23                    folkswithhats                                6.6 k
 freetype-freeworld                   x86_64               2.6-1.fc23                      rpmfusion-free-updates-testing               408 k
 google-noto-sans-fonts               noarch               20150417-2.fc23                 fedora                                       516 k

Transaction Summary
==============================================================================================================================================
Install  3 Packages

Total download size: 930 k
Installed size: 2.0 M
Downloading Packages:
(1/3): google-noto-sans-fonts-20150417-2.fc23.noarch.rpm                                                      4.6 MB/s | 516 kB     00:00    
(2/3): fedy-font-config-1.0.1-1.fc23.noarch.rpm                                                                14 kB/s | 6.6 kB     00:00    
(3/3): freetype-freeworld-2.6-1.fc23.x86_64.rpm                                                               740 kB/s | 408 kB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                         567 kB/s | 930 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : freetype-freeworld-2.6-1.fc23.x86_64                                                                                      1/3 
  Installing  : google-noto-sans-fonts-20150417-2.fc23.noarch                                                                             2/3 
  Installing  : fedy-font-config-1.0.1-1.fc23.noarch                                                                                      3/3 
  Verifying   : fedy-font-config-1.0.1-1.fc23.noarch                                                                                      1/3 
  Verifying   : google-noto-sans-fonts-20150417-2.fc23.noarch                                                                             2/3 
  Verifying   : freetype-freeworld-2.6-1.fc23.x86_64                                                                                      3/3 

Installed:
  fedy-font-config.noarch 1.0.1-1.fc23        freetype-freeworld.x86_64 2.6-1.fc23        google-noto-sans-fonts.noarch 20150417-2.fc23       

Complete!
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by Abhinav1217** [comment]
Font-config has installed correctly.  

Error in notification can be due to difference in Cinnamon and Gnome shell.  We will look into it. Thanks.

**Comment by ilovemysillybanana** [comment]
I'm actually still getting this issue right now, just did a fresh install of Fedora 24 Cinnamon Spin and this is the output I got when I tried installing Better Font Rendering.

```
[jtobar@localhost ~]$ sudo fedy
[sudo] password for jtobar: 
Last metadata expiration check: 0:26:01 ago on Sat Oct 15 14:38:35 2016.
Dependencies resolved.
================================================================================
 Package               Arch        Version             Repository          Size
================================================================================
Installing:
 fedy-font-config      noarch      1.0.1-1.fc24        folkswithhats      6.6 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 6.6 k
Installed size: 699  
Downloading Packages:
fedy-font-config-1.0.1-1.fc24.noarch.rpm         12 kB/s | 6.6 kB     00:00    
--------------------------------------------------------------------------------
Total                                            12 kB/s | 6.6 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : fedy-font-config-1.0.1-1.fc24.noarch                        1/1 
  Verifying   : fedy-font-config-1.0.1-1.fc24.noarch                        1/1 

Installed:
  fedy-font-config.noarch 1.0.1-1.fc24                                          

Complete!
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

```

**Comment by Abhinav1217** [comment]
I am currently updating fedy and fedy-font-config for F25. I will be updating it soon.

**Comment by bddenhartog** [comment]
I'm closing this as F23 reached end-of-life on 2016-12-20: http://fedoraproject.org/wiki/End_of_life

**Comment by vbsteja** [comment]
Guys, i am using F25, same problem faced when tried to setup the better font rendering, any update on this?

**Comment by bddenhartog** [comment]
@vbsteja I was able to run it successfully on my workstation, but I haven't tested it on a brand new installation yet. Can you give me a bit more information to help me debug this for you?

- What DE are you using? Gnome, cinnamon, etc.

- Are you receiving the same `No such schema` error?

**Comment by vbsteja** [comment]
@bddenhartog i am using Cinnamon DE. yes i am getting the same error running from the Terminal. on the other side i tried with installing gnome and setting up the fonts and got the same error.

 i have heard the  fontconfig-ultimate are better in rendering, any news including them in repos? or already included?
thanks.

**Comment by Abhinav1217** [comment]
In my tests, I got errors in Gnome Xorg and Cinnamon, but not on KDE and Gnome Wayland. So I will search for if gnome guys made some Xorg incompatiable changes for wayland support .

**Comment by Abhinav1217** [comment]
@vbsteja We have taken lots of tipes from fontconfig-ultimate in our own font-config. There has been somewhat discussion at #149 about this which you can check.

**Comment by vbsteja** [comment]
thanks @Abhinav1217, looking forward for your findings in Cinnamon and Gnome Xorg.

**Comment by Abhinav1217** [comment]
@vbsteja Gnome is not really known for its documentations, and google search is not helping much. Even more confusing, I took a fresh Gnome VM and I did not face any error on Xorg session.  But this was before I did system update. On a VM after running system update, I got the error. So its a progress.

**Comment by Abhinav1217** [comment]
@vbsteja Gnome is not really known for its documentations, and google search is not helping much. Even more confusing, I took a fresh Gnome VM and I did not face any error on Xorg session.  But this was before I did system update. On a VM after running system update, I got the error. So its a progress.
