### ISSUE TITLE
Add Remove button for now removed apps

### ISSUE THREAD

**Issue by gitgt** [fedy/fedy#342]
It's OK about removing apps from Fedy in terms from preventing new installs, like discussed in #291. 
But there should still be "Remove" button for those apps, maybe in a new tab. Please consider that.

Fox example, I installed Popcorn before through Fedy, and I want to remove it also there. 
That would also give me a hint which apps are removed now, signaling they had reason to be removed.

**Comment by satya164** [comment]
@gitgt IMHO better will be to have a doc with uninstallation instructions rather than having unused plugins in the code.

**Comment by DStewart1997** [comment]
Speaking of Popcorn Time - [it looks like it might be back...](https://blog.popcorntime.sh/official-statement/)

**Comment by bddenhartog** [comment]
@satya164 not to necro a dead thread, but adding that post-receive hook is something I could create and host on one of my clusters; although my schedule is a bit busy right now and this may take some time to perfect, between development and testing.
