### ISSUE TITLE
Install Dropbox daemon only for non-GNOME DEs

### ISSUE THREAD

**Issue by jacek99** [fedy/fedy#364]
Running Fedy on Fedora 23 XFCE, the Dropbox option wants to install Dropbox together with Nautilus.

It would be great if Fedy could detect a non-GNOME DE and install just the daemon + set it up to run automatically on start up.

Had to do a manual install for my XFCE laptop.

Thanks!

**Comment by bheru27** [comment]
@jacek99  I feel sorry for you since you didn't get a response, what did you do to install it without nautilus? did you follow the headless setup on https://www.dropbox.com/install-linux ?

**Comment by jacek99** [comment]
Well, I switched to GNOME eventually, so I guess it is a non-issue for me at this point. But probably still valid for any non-GNOME users

**Comment by bddenhartog** [comment]
@jacek99 as bheru asked, are you able to let us know what steps you took to install, if different at all from the [headless instructions](https://www.dropbox.com/install-linux#linux-install-content)?
