### ISSUE TITLE
RealVNC Server?

### ISSUE THREAD

**Issue by geek1011** [fedy/fedy#400]
Would it be possible to add RealVNC Server?

**Comment by Abhinav1217** [comment]
Hit me with some links and I will see if it is possible.

**Comment by geek1011** [comment]
https://www.realvnc.com/download/vnc/linux/

**Comment by geek1011** [comment]
But they just changed the download method, so It cannot be automatically downloaded easily anymore

**Comment by geek1011** [comment]
Inside the .tar.gz for RPM x64, there are 2 RPMs: server and viewer.
