### ISSUE TITLE
Add Unity3D

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#420]
Originally reported in folkswithhats/fedy-plugins-developers:

@bil-elmoussaoui 

> Add Unity3D Editor. 
> There's a bash script to install the editor but there's some missing dependencies like `libpq.so.5`. And the desktop file is not created automatically.. Something worth to be added to Fedy Developers plugins ;)  

@Abhinav1217 

> We shall look into it. A pull request would be welcome.

@danstewart 

> Here's a link to the forum post regarding Unity on Linux.
> It includes a breakdown of all the dependencies too, will have a look into it but will leave the link here for anyone else interested in creating the installer.
> 
> http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by danstewart** [comment]
Looks like there's now an official beta platform-agnostic shell script to install this.
It is 2.2GB though...

Looks like that thread linked above:
https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

Is still where the latest download link will be.

**Comment by danstewart** [comment]
It also has the following lines:

```shell
EXTRACT_SUBDIR="${EXTRACT_DIRECTORY}/unity-editor-5.6.0xb3Linux"
echo "Installer for Unity 5.6.0xb3Linux"
echo ""
echo "Press Enter to begin extracting to ${EXTRACT_SUBDIR}"
read meh
```

We can specify the extract dir using the `-o` or `--output` flags.
I'm not aware of any easy way to ignore the read line outwith using sed or perl to remove it (`s/read meh//g`).

After this it extracts the file (which is within the shell script) and then tells you to run it - so I'm guessing it's probhably a graphical installer.

**Comment by satya164** [comment]
This sounds like a candidate for the community repo.

**Comment by bddenhartog** [comment]
Agreed - flagged it for now (so it is easily discoverable in the future when community repo is implemented)
