### ISSUE TITLE
Enable community plugins

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#422]
We receive a lot of issues and pull requests for plugins that we do not, for one reason or another, accept as an official plugin. Usually, this is because the plugin fits a niche role, or there are already alternatives in Fedy, or the plugin isn't actively maintained (or at least, not maintained as actively as we want). Ultimately, this is detrimental to the community as a whole, as users miss out on the discovery and ease of installation of various applications and tools that they might not necessarily be exposed to; additionally, two users who want the same niche application added must each individually add and manage their own Fedy plugin.

In order to ease these issues, we are planning on implementing "community plugins". The implementation details have yet to be planned out, but the initial thought is that you will be able to easily browse and enable community-built plugins via the GUI.

Initial thoughts:

- Both `main` and `community` plugin repositories will be abstracted away from the `fedy` repository. `main` and `community` repositories will be separate from each other, with different standards for maintenance and acceptance. The FWH team will not officially support (add, fix, or otherwise modify) community plugins, but we will review them before acceptance (for security and other reasons).

- The `fedy` repository will include only the UI elements, and the Fedy application will no longer ship with any plugin instructions. Instead, it will call out to the `main` and `community` repositories for the _current_ plugin list, and display as needed. This will allow for dynamic updating of plugin lists, much like users are used to from other package managers.

- The `community` repository will be more lenient in the plugins that are accepted, which means that effectively, if someone wants their niche program or library or some alternative to a `main` plugin to be available via Fedy, they will be able to create a `community` plugin and submit it for review. We'll make sure it's formatted correctly and will work, and as long as everything is on the up-and-up, it will be accepted. We'll also deprecate plugins that become unmaintained, and remove any that need removal (either by the author's request or because it's broken in some sense). We (as a team) will not maintain these plugins, although it is possible that team members maintain their own community plugins (we do use Fedy, after all).

- The `main` repository will continue to be more restrictive in the plugins we accept. Generally, we want to keep general-purpose, popular, useful plugins in `main`. These plugins will be officially supported, meaning that the Fedy team will keep them up-to-date and work on issues as needed. There may be some reorganization of the plugins currently in core when the community repository is available.

**Please feel free to discuss.** Fedy is a community-driven application, and all feedback is appreciated.

**Comment by danstewart** [comment]
Additional comments from @bddenhartog 

>\- core: solid, tested plugins that are very general, and do not depend on or require user-specific configuration to work; things like "install pycharm" should just install pycharm and be available for everyone. another example might be setting up sources from release teams - eg docker, and installing the program, making post-install modifications, etc. these will likely end up being mostly "tools" rather than "fun apps", just due to the nature of what we want to provide support for.
\
\- community: johnny wants to make a plugin so it's easy for people to get a cool bash prompt, or install a user-specific thing, so he does that and has it on his github - cool. unfortunately his github account doesn't have nearly as much visibility as ours, so his plugin goes mostly unnoticed, even though other people might like to take advantage of it. so johnny can submit a pr to add his plugin to the community repo, which will show up in fedy.

**Comment by gitgt** [comment]
This was an idea in Please add Chromium #260 and I guess it's still valid.

**Comment by sudoforge** [comment]
Closing as irrelevant due to #607. Users who wish to provide software for others in the community will be able to do so (and have it displayed in Fedy) by creating a COPR repository.
