### ISSUE TITLE
Refactor Fedy to pull from the official plugin library

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#447]
This issue is one of the subtasks on the road to completing #422.

---

A new repository has been created to house all officially supported plugins: [folkswithhats/library](https://github.com/folkswithhats/library)

Fedy should be refactored to query and display plugins from the `library` repository, instead of being bundled with the RPM package.

- [ ] folkswithhats/library#2 is closed
- [ ] All plugins have been removed from the `fedy` repository, and the application now polls the `library` repository for plugin data
- [ ] Documentation for contributing has been added, both for the `fedy` application and plugins in `library`, in their respective repositories

**Comment by satya164** [comment]
Have you thought about the development workflow? It should still be possible to use installed plugins.

**Comment by bddenhartog** [comment]
@satya164 
> Have you thought about the development workflow? It should still be possible to use installed plugins.

I'll be keeping `library` up-to-date with plugins in this repository until they are ready to be removed, and no plugins are actually going to be modified with the migration to `library`. Well, technically I'm going to do all of the other work (without merging) before migrating the plugins (to lessen time between migration to `library` and polling update to the application), but that's beside the point.

**Comment by satya164** [comment]
I'm not sure what you mean. I was saying that locally installed plugins still need to be supported, otherwise it'll be impossible to work on plugins.

**Comment by bddenhartog** [comment]
Ah, I see what you're getting at.

Yes, the current plan is to allow directories in a user-specified directory to override plugins from the remote. (e.g. if `~/code/my-fedy-plugins/chrome` exists, this will be used instead of the remote's plugin). Although I think we could do a lot better by providing a sandbox environment for contributors to work in, so the main system isn't affected by any changes made during development.

**Comment by xasx** [comment]
To test own plugins one could perhaps also specify something like a 'private plugin repo' URL, which may point to a user's fork of the plugins repo. On the other hand that would involve remote lots of communication that might be undesirable, especially if there are many small fixes to be committed during development…

**Comment by sudoforge** [comment]
Closing in preference of #607.
