### ISSUE TITLE
Gitkraken requires libcurl-gnutls, and auto updating of GitKraken

### ISSUE THREAD

**Issue by ryanvade** [fedy/fedy#540]
GitKraken 3.1.1 requires libcurl-gnutls.so.4.   If I symlink /usr/lib64/libcurl.so.4 with /usr/lib64/libcurl-gnutls.so.4 it runs without issue.  3.1.1 also fixes the file explorer localization bugs so it would be nice to have an auto-update feature for GitKraken instead of having to delete the gitkraken cache folder.

**Comment by 4ppleboy** [comment]
+

**Comment by Abhinav1217** [comment]
>  If I symlink /usr/lib64/libcurl.so.4 with /usr/lib64/libcurl-gnutls.so.4 it runs without issue.
[This guy](https://gist.github.com/aelkz/17528d2f6a5db73185c7dfbd28e49d18#gistcomment-2225788) suggests we can create a symlink in the /opt/gitkraken folder too.    I am started testing both, yours and his, workaround. I will update the plugin with whatever works best. If possible, we should avoid making changes on users lib64 folder. 

>  it would be nice to have an auto-update feature for GitKraken.

This should be best if asked to the gitkraken developers. Currently they don't even provide RPM packages which is really sad.  There are 4 copr for gitkraken, but none of them seems keeping themselves updated. Even Atom does not have an inbuilt update mechanism. We have to reinstall rpm every time we have to update it. Good thing is that [they have provided](https://support.gitkraken.com/how-to-install) a somewhat official script to update gitkraken. User data location is separately located, so I don't see why you need to delete cache folder.

**Comment by ryanvade** [comment]
My apologies for not responding sooner. 

I was thinking it would be nice if Fedy were to check for updates to software not packaged as RPMs and perform the upgrade itself.  The cache I am referring to is Fedy's package cache, I deleted gitkraken from it and re-ran the install which installed the newer version.

**Comment by bddenhartog** [comment]
Oof. This was unlabeled and escaped my notice. I'm going through issues and assigning appropriate labels. Is this still something that needs to be looked into?
