### ISSUE TITLE
[Proposition] Some options and expansion of the functionality.

### ISSUE THREAD

**Issue by aevernum** [fedy/fedy#573]
Expand the number of tabs, and various third-party software.
Make the first tab, with the ability to connect third-party repositories, such as a rpmfusion, RFRemix, negativo17 and others.
if you want, i can help, i have time for this :)

**Comment by bddenhartog** [comment]
I'm in the process of building a new UI. Please reformat your requests into a list, or at least make it finite ("and others" isn't something that can be reviewed/approved/discussed)

**Comment by aevernum** [comment]
Thanks, I understood where to start.
