### ISSUE TITLE
Brackets should be removed

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#575]
In #574, it was determined that the plugin for Brackets was using a heavily outdated COPR. An updated source for installation should be found; if one is not available, the plugin should be removed.

**Comment by Xmetalfanx** [comment]
seeing this "issue" and browsing around a bit, I found this  https://github.com/adobe/brackets/issues/14036 mentioning Brackets on Fedora 27..... also on the Brackets github page (this may be worth keeping an eye one, i suppose) https://github.com/adobe/brackets/issues/14135 asking for (among other distros) "Fedora Support"
