### ISSUE TITLE
Simplenote Plugin issue

### ISSUE THREAD

**Issue by jonbybc74** [fedy/fedy#581]
Fedy unable to install new versions of Simplenote ( only the old version )

Seems like Simplenote guys made a change in its filename pattern

In fedy script its appear as
 Simplenote-linux-x64.[0-9.]{5}.tar.gz
but the new filename pattern is
Simplenote-linux.[0-9.]{5}.tar.gz

After removing "-x64" seems like the new version is installed with Fedy.

Please verify.

**Comment by jonbybc74** [comment]
I just offer a solution. can you commit changes to code?

**Comment by sudoforge** [comment]
@jonbybc74 A patch will be applied to address this in the next release.
