### ISSUE TITLE
[Request] Pop!_OS theme

### ISSUE THREAD

**Issue by jurf** [fedy/fedy#582]
https://github.com/pop-os/gtk-theme

It looks really neat, it would be nice to be able to get it under Fedora.

Cheers.

**Comment by jurf** [comment]
I’ve just realised that it’s already present in the archives as `pop-gtk-theme.noarch`, it just isn’t visible in GNOME Software `>.<` Sorry for the buzz.

**Comment by sudoforge** [comment]
Good find - I hadn't yet had a chance to take a look at this.
