### ISSUE TITLE
menu does not render properly on Fedora KDE 28

### ISSUE THREAD

**Issue by RafalSkolasinski** [fedy/fedy#598]
As on screenshot. On Fedora KDE 28 Fedy's menu does not render properly.
I didn't notice anything similar in other applications.

![screenshot_20180602_122358](https://user-images.githubusercontent.com/10928117/40873410-d49d950c-665f-11e8-84d8-01fa214df1d7.png)

**Comment by sudoforge** [comment]
@RafalSkolasinski Can you run Fedy from the terminal, and check to see if there are any warnings or error messages displayed?

**Comment by sudoforge** [comment]
To note - please include any stdout/stderr you do receive in a comment here.

Dank je!

**Comment by RafalSkolasinski** [comment]
I did start Fedy from a terminal. The only thing that got displayed is
```
➜  ~ fedy
Gjs-Message: 14:37:54.101: JS WARNING: [./app.js 535]: reference to undefined property "license"
```

**Comment by sudoforge** [comment]
I was not able to reproduce this in a live image using the [KDE Plasma Spin][1]:

![20180603_134252675][img-vm]

[img-vm]: https://user-images.githubusercontent.com/3893293/40891060-7e356958-6734-11e8-988f-d91be69276f7.png

> This is almost fresh Fedora 28 KDE install

What, exactly, have you changed/configured post installation?

> I have nvidia card but I didn't install any drivers by hand. I guess Fedora installed by default opensource drivers.

Can you try rolling back the nouveau drivers, or installing the proprietary nvidia drivers, and letting me know if this solves the issue?

[1]: https://spins.fedoraproject.org/kde/download/index.html
[2]:

**Comment by sudoforge** [comment]
I was not able to reproduce this in a live image using the [KDE Plasma Spin][1]:

![20180603_134252675][img-vm]

[img-vm]: https://user-images.githubusercontent.com/3893293/40891060-7e356958-6734-11e8-988f-d91be69276f7.png

> This is almost fresh Fedora 28 KDE install

What, exactly, have you changed/configured post installation?

> I have nvidia card but I didn't install any drivers by hand. I guess Fedora installed by default opensource drivers.

Can you try rolling back the nouveau drivers, or installing the proprietary nvidia drivers, and letting me know if this solves the issue?

[1]: https://spins.fedoraproject.org/kde/download/index.html

**Comment by sudoforge** [comment]
> Can you try rolling back the nouveau drivers, or installing the proprietary nvidia drivers, and letting me know if this solves the issue?

I'm leading with your graphics card/driver as the source of the issue currently, as I'm testing using an Intel HD 5500 chip and am not able to reproduce this.

**Comment by RafalSkolasinski** [comment]
After installing the proprietary driver the issue is gone. 

The only funny thing is that without it everything else works better, only Fedy has this glitches when I hover my mouse over the menu. When I install proprietary driver ``xorg-x11-drv-nvidia`` everything else is working slightly worse...

**Comment by RafalSkolasinski** [comment]
I just checked: the issue also appear on Gnome, so is not KDE specific.

**Comment by sudoforge** [comment]
> After installing the proprietary driver the issue is gone.

Thought that might be the case.

> I just checked: the issue also appear on Gnome, so is not KDE specific.

Well of course it won't be DE specific; the issue is with your GPU(s) and driver.

Is there anything funky in the `dmesg` log when you run `fedy`?

**Comment by RafalSkolasinski** [comment]
> Well of course it won't be DE specific; the issue is with your GPU(s) and
driver.

Sometimes certain apps behave differently on qt and gtk, didn't hurt to
check.

> Is there anything funky in the dmesg log when you run fedy?

I do not see anything appearing there at all when running fedy.





--
Rafał Skolasiński

GitHub: https://github.com/RafalSkolasinski
Kwant GitLab: https://gitlab.kwant-project.org/r-j-skolasinski

**Comment by sudoforge** [comment]
How about in your Xorg log?

@fedy/team if someone has an nvidia card and can attempt to reproduce this, that'd be great

**Comment by RafalSkolasinski** [comment]
I do not see anything in ``/etc/var/Xorg.0.log`` when running Fedy.

In addition I just tested in the Live KDE Fedora from USB Stick.
The only changes to live system I did was execution of instructions on
fedys webpage.
I confirm that I still have bug in this situation.

The graphic card is nvidia 970 GTX





--
Rafał Skolasiński

GitHub: https://github.com/RafalSkolasinski
Kwant GitLab: https://gitlab.kwant-project.org/r-j-skolasinski

**Comment by sudoforge** [comment]
What if you rolled the nouveau drivers back to a previous version?

**Comment by RafalSkolasinski** [comment]
How can I do it? I do not see different version for Fedora 28 than
``xorg-x11-drv-nouveau-1.0.15-4.fc28.x86_64.rpm``





--
Rafał Skolasiński

GitHub: https://github.com/RafalSkolasinski
Kwant GitLab: https://gitlab.kwant-project.org/r-j-skolasinski

**Comment by sudoforge** [comment]
@RafalSkolasinski I made that suggestion without checking the packages. At this time, `1.0.15-4` is the latest available release of that package for F28.

@fedy/team It would still be helpful for anyone with an NVIDIA card to spin up an F28 (KDE) VM and test this.

**Comment by RafalSkolasinski** [comment]
It may be easier to boot a Live USB. I checked that the issue is also
present then.





--
Rafał Skolasiński

GitHub: https://github.com/RafalSkolasinski
Kwant GitLab: https://gitlab.kwant-project.org/r-j-skolasinski

**Comment by sudoforge** [comment]
Booting with a Live USB or in a VM won't make a difference. The issue is tied to the nouveau driver and an NVidia card, so as long as the tester is running F28 on a machine with an NVidia GPU, they should encounter the issue.

**Comment by sudoforge** [comment]
@RafalSkolasinski do you still experience this with the latest NVIDIA drivers?

**Comment by sudoforge** [comment]
Closing; unable to reproduce, lack of activity from the submitter.
