### ISSUE TITLE
Popcorn not lauching on fedora 28

### ISSUE THREAD

**Issue by andresimi** [fedy/fedy#608]
The popcorn do not work on fedora 28. 
The install is ok, but when I try to run the program, the following error appears:

[23167: 23167: 0714/192846: ERROR: browser_main_loop.cc (260)] Gtk: Could not find the themes tool in module_path: "murrine"

**Comment by sudoforge** [comment]
This is not a Fedy issue; you see that error because you are missing the `gtk2-engines` package.

**Comment by andresimi** [comment]
Hi, according this (https://github.com/popcorn-official/popcorn-desktop/issues/776), popcorn 3.10 don't run on fedora 28. Maybe fedy should considerate downgrade to 3.9. Thank you.
