### ISSUE TITLE
Add jq as a dependency

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#623]
This will allow us to use `jq` in installation scripts, which will be useful when using third party APIs (such as the GitHub API) to determine download URIs.

**Comment by narendravardi** [comment]
@sudoforge, can i pick this up?

**Comment by sudoforge** [comment]
@narendavi This was actually closed in #624 - it was necessary for something I requested in #622, so I just fired it off quickly. 

Thanks for checking first! Any other of the [hacktoberfest issues][0] should be pretty quick - let me know if you have any questions. 

[0]: https://github.com/fedy/fedy/labels/hacktoberfest
