### ISSUE TITLE
Remove the '.plugin' suffix from plugin directories

### ISSUE THREAD

**Issue by sudoforge** [fedy/fedy#628]
The `.plugin` suffix in directories is extraneous and unecessary, as they already reside in `/plugins`. We should remove the suffix from the directories and update all references that may include the suffix.

**Comment by jonas-martinez** [comment]
Hi ! I am new on Github but I would like to try working on this issue

**Comment by sudoforge** [comment]
@jonas-martinez Feel free to pick it up!
