### ISSUE TITLE
[Request] some tweaks for better UI

### ISSUE THREAD

**Issue by jeffshee** [fedy/fedy#638]
Hi, please consider add these into `Tweaks` section if u find them useful.
1. QGtkStyle for better Qt integration in Gnome environment, source from here: [ArchLinux](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications)
Install `qt5-qtstyleplugins`
Append below lines into .bash_profile
```
QT_QPA_PLATFORMTHEME="gtk2"
export QT_QPA_PLATFORMTHEME
```

2. A quick workaround for Wine blurry text rendering (this probably never get fixed... )
source from here: [ArchLinux](https://bbs.archlinux.org/viewtopic.php?id=217309)
Append below lines into .bash_profile
```
FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export FREETYPE_PROPERTIES
```

**Comment by sudoforge** [comment]
@jeffshee My apologies, this wasn't labeled appropriately and never got my attention. Is this still something you think would be a good idea? I don't use Gnome, so I'm not 100% sure how the above envvars would play out.

**Comment by jeffshee** [comment]
@sudoforge Is fine tho =) It was my fault for not label it properly =P
The 1st one is for the theme engine setup. It works with most of the QT apps, (QT apps adopt the gtk theme so they look more integrated to the system itself), but will also potentially break some app, for example VirtualBox, which then require to clear such envvar before launch the app. So I'm not sure whether it is a good idea or not...

The 2nd one I couldn't confirm the effect any more. It seems recent build of wine got the text rendering bug fixed already. Now even after I clear the envvar, the text rendering is working just fine. Need a double-check.

**Comment by sudoforge** [comment]
Sounds like something that might be user-specific, and should not be integrated into Fedy. Thanks for the suggestions, though!
