### ISSUE TITLE
Dino icon image too large?

### ISSUE THREAD

**Issue by svenevs** [fedy/fedy#644]
Just installed from source following directions here https://github.com/fedy/fedy/issues/632#issuecomment-466655124

![dino](https://user-images.githubusercontent.com/5871461/54626501-80b7f000-4a2e-11e9-9c0b-133a4dfa9cc1.png)

Should Dino be that big? I love the icon so it doesn't matter much to me.  I tried to look around but am not very familiar with how fedy works...happy to provide any testing with guidance, if fix is simple I'll send PR?

Thanks for Fedy, happy "customer" for years :slightly_smiling_face:

**Comment by sudoforge** [comment]
Well, you can't expect a _dinosaur_ to be small and byte-sized, now can you? :)

Thanks for noticing this. I'll spin up a VM and attempt to recreate it as soon as I am able.

**Comment by danstewart** [comment]
PR #652 resizes the icons until a better fix is implemented.

Looks like we only scale the icons if they exist on the icon pack you use - if we use the icon that's bundled with fedy we just display it as the actual size.

Unsure why this only happens when building from source though...
