### ISSUE TITLE
Too many arguments to function GLib.timeout_add

### ISSUE THREAD

**Issue by f6p** [fedy/fedy#657]
I recently installed fedy.

When I try to install application (like chrome or skype for example) "Task failed!" notification pops up. When I start fedy from terminal after clicking application install button the output shows:
```
This incident has been reported.
Gjs-Message: 10:23:48.585: JS WARNING: [./app.js 411]: Too many arguments to function GLib.timeout_add: expected 3, got 4
```
System: Fedora 30.

**Comment by danstewart** [comment]
Thanks for the bug report.
PR #658 resolves the issue with the notification always saying failed.
PR #659 resolves an additional issue with the chrome install.
